<!-- Этот блок кода нужно вставить в ту часть страницы, где вы хотите разместить карту  (начало) -->
<script src="http://api-maps.yandex.ru/1.1/?key=AJ9D0UsBAAAAWwtGHAIAT1CfawFEnHDkDRuH1peKENqgF98AAAAAAAAAAADSvxJLq9plruBxuZeEu2haYJfQ-g==~AOyVrUwBAAAAv9WzNwIAqQP1nYmZWvJz632tqZktqQprSJwAAAAAAAAAAADloKxo2FCP8Zb708EiyB8lSNr_Sg==~AMUgUU0BAAAA_J1GAAIAcNk1NAZvCCXxqAq_mUAolrKXsksAAAAAAAAAAACihNWVxL0mGn8D3jsnNr34a4WoLQ==~ADchUU0BAAAAnrn_LQIAewArExbwxOyPZ0Sp9xFpSbsgUjMAAAAAAAAAAACJ5e_fLOm-XDcMO8LumTgiJWnTsw==&wizard=constructor" type="text/javascript"></script>
<script type="text/javascript">
    YMaps.jQuery(window).load(function () {
        var map = new YMaps.Map(YMaps.jQuery("#YMapsID-1357")[0]);
        map.setCenter(new YMaps.GeoPoint(39.703373,54.644961), 11, YMaps.MapType.MAP);
        map.addControl(new YMaps.Zoom());
        map.addControl(new YMaps.ToolBar());
        map.addControl(new YMaps.TypeControl());

        YMaps.Styles.add("constructor#pmgrm1Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm1.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm2Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm2.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm3Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm3.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm4Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm4.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm5Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm5.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm6Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm6.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
        YMaps.Styles.add("constructor#pmgrm7Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm7.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm8Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm8.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm9Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm9.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm10Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm10.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm11Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm11.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm12Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm12.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm13Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm13.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm14Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm14.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		 YMaps.Styles.add("constructor#pmgrm15Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm15.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm16Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm16.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm17Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm17.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm18Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm18.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm19Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm19.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm20Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm20.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm21Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm21.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm22Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm22.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm23Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm23.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });

		YMaps.Styles.add("constructor#pmgrm24Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm24.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm25Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm25.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });
		YMaps.Styles.add("constructor#pmgrm26Placemark", {
            iconStyle : {
                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmgrm26.png",
                size : new YMaps.Point(28,29),
                offset: new YMaps.Point(-8,-27)
            }
        });

       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.752522,54.6206), "constructor#pmgrm1Placemark", "Прио-Внешторгбанк, ЦО<br/><br/>Рязань, ул.Есенина, 82/26<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;9.38&Prime;<br />Широта: 54&deg;37&prime;13.98&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.759871,54.625151), "constructor#pmgrm5Placemark", "Центральный Дворец детского творчества, главный корпус<br/><br/>Рязань, Ул.Есенина, 46<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;35.23&Prime;<br />Широта: 54&deg;37&prime;30.81&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.758948,54.625269), "constructor#pmgrm2Placemark", "Центральный Дворец детского творчества, спортивный зал<br/><br/>Рязань, Ул.Есенина, 46<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;32.14&Prime;<br />Широта: 54&deg;37&prime;30.99&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.713254,54.609305), "constructor#pmgrm3Placemark", "Прио-Внешторгбанк, ОПК 6<br/><br/>Рязань, ул.Черновицкая, 1/77<br /><br />GPS координаты:<br />Долгота: 39&deg;42&prime;47.53&Prime;<br />Широта: 54&deg;36&prime;33.59&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.657174,54.644663), "constructor#pmgrm4Placemark", "Прио-Внешторгбанк, ОПК 8<br/><br/>Рязань, ул.Московское шоссе, 51/2<br /><br />GPS координаты:<br />Долгота: 39&deg;39&prime;25.95&Prime;<br />Широта: 54&deg;38&prime;40.74&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.642744,54.677683), "constructor#pmgrm7Placemark", "\"Рязань-лада\"<br/><br/>Рязань, ул.Бирюзова, д.1Г<br /><br />GPS координаты:<br />Долгота: 39&deg;38&prime;33.96&Prime;<br />Широта: 54&deg;40&prime;39.93&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.712417,54.62751), "constructor#pmgrm6Placemark", "ДО Промышленное отделение<br/><br/>Рязань, пр.Завражнова, д.5<br /><br />GPS координаты:<br />Долгота: 39&deg;42&prime;45.36&Prime;<br />Широта: 54&deg;37&prime;38.99&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.756266,54.616429), "constructor#pmgrm8Placemark", "Областная налоговая консультанция<br/><br/>Рязань, ул.Новая, 69/12<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;22.13&Prime;<br />Широта: 54&deg;36&prime;59.38&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.724144,54.613583), "constructor#pmgrm9Placemark", "Рязанский государственный радиотехнический университет<br /><br />Рязань, ул.Гагарина, 59/1<br /><br />GPS координаты:<br />Долгота: 39&deg;43&prime;26.92&Prime;<br />Широта: 54&deg;36&prime;48.9&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.64332,54.66115), "constructor#pmgrm10Placemark", "ДО ОПК5<br /><br />Рязань, ул.Октябрьская, 28<br /><br />GPS координаты:<br />Долгота: 39&deg;38&prime;35.95&Prime;<br />Широта: 54&deg;39&prime;40.14&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.80383,54.61053), "constructor#pmgrm11Placemark", "ДО ОПК7<br /><br />Рязань, ул.Новоселов, 21А<br /><br />GPS координаты:<br />Долгота: 39&deg;48&prime;13.79&Prime;<br />Широта: 54&deg;36&prime;37.91&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.76425,54.62947), "constructor#pmgrm12Placemark", "ДО ОПК4<br /><br />Рязань, ул.Грибоедова, 24/5<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;51.3&Prime;<br />Широта: 54&deg;37&prime;46.09&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.764009,54.61941), "constructor#pmgrm13Placemark", "НОУ ВПО «Санкт-Петербургский университет управления и экономики»<br /><br />Рязань, ул.Электрозаводская, 52<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;50.43&Prime;<br />Широта: 54&deg;37&prime;9.88&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.701946,54.625066), "constructor#pmgrm14Placemark", "ф-ка «Красный октябрь»<br /><br />Рязань, ул. Чкалова, 19Г<br /><br />GPS координаты:<br />Долгота: 39&deg;41&prime;45.06&Prime;<br />Широта: 54&deg;37&prime;18.2&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.751451,54.584111), "constructor#pmgrm15Placemark", "Общество «Автогарант»<br /><br />Рязань, ул. Рязанская, 22А<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;5.22&Prime;<br />Широта: 54&deg;35&prime;2.8&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.644727,54.681431), "constructor#pmgrm16Placemark", "РПТП «Гранит»<br /><br />Рязань, ул. Интернациональная, 1Г<br /><br />GPS координаты:<br />Долгота: 39&deg;38&prime;41.02&Prime;<br />Широта: 54&deg;40&prime;53.15&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.691854,54.619204), "constructor#pmgrm17Placemark", "ООО «Вектра»<br /><br />Рязань, ул. Чкалова, 29<br /><br />GPS координаты:<br />Долгота: 39&deg;41&prime;30.67&Prime;<br />Широта: 54&deg;37&prime;9.13&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.637505,54.655991), "constructor#pmgrm18Placemark", "ИП Почтарев<br /><br />Рязань, ул. Магистральная, 10А<br /><br />GPS координаты:<br />Долгота: 39&deg;38&prime;15.02&Prime;<br />Широта: 54&deg;39&prime;21.57&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.764304,54.621697), "constructor#pmgrm19Placemark", "ОАО Рязанский Радиозавод<br /><br />Рязань, ул. Лермонтова, 11<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;51.49&Prime;<br />Широта: 54&deg;37&prime;18.11&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.726489,54.62959), "constructor#pmgrm20Placemark", "ОПК 9<br /><br />Рязань, ул. Первомайский пр-т, 34<br /><br />GPS координаты:<br />Долгота: 39&deg;43&prime;35.36&Prime;<br />Широта: 54&deg;37&prime;46.52&Prime;"));
	   map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.667546,54.664274), "constructor#pmgrm21Placemark", "ОПК 10<br /><br />Рязань, ул. Интернациональная, 22а<br /><br />GPS координаты:<br />Долгота: 39&deg;40&prime;3.17&Prime;<br />Широта: 54&deg;39&prime;51.39&Prime;"));

       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.633506,54.675428), "constructor#pmgrm22Placemark", "з-д «ТЯЖПРЕССМАШ»<br />(<em>находится в закрытой зоне</em>)<br /><br />GPS координаты:<br />Долгота: 39&deg;38&prime;0.76&Prime;Широта: 54&deg;40&prime;31.45&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.692901,54.616045), "constructor#pmgrm23Placemark", "м-н «Продукты»<br /><br />Рязань, ул. Островского, 105А<br /><br />GPS координаты:<br />Долгота: 39&deg;41&prime;34.41&Prime;<br />Широта: 54&deg;36&prime;57.82&Prime;"));

       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.655329,54.63394), "constructor#pmgrm24Placemark", "м-н «Рамфуд»<br /><br />Рязань, ул. Костычева, 9<br /><br />GPS координаты:<br />Долгота: 39&deg;39&prime;19.18&Prime;<br />Широта: 54&deg;38&prime;2.18&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.754388,54.62329), "constructor#pmgrm25Placemark", "Автошкола «Ягуар» (ТЦ «Маяк»)<br /><br />Рязань, ул. Ленина, 10<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;15.8&Prime;<br />Широта: 54&deg;37&prime;23.84&Prime;"));
       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(39.755279,54.620582), "constructor#pmgrm26Placemark", "Паспортно-визовый центр<br /><br />Рязань, ул. Есенина, 41<br /><br />GPS координаты:<br />Долгота: 39&deg;45&prime;19&Prime;<br />Широта: 54&deg;37&prime;14.1&Prime;"));
	   
        function createObject (type, point, style, description) {
            var allowObjects = ["Placemark", "Polyline", "Polygon"],
                index = YMaps.jQuery.inArray( type, allowObjects),
                constructor = allowObjects[(index == -1) ? 0 : index];
                description = description || "";
            
            var object = new YMaps[constructor](point, {style: style, hasBalloon : !!description});
            object.description = description;
            
            return object;
        }
    });
</script>

<div style="position: relative; text-align: center; padding: 20px 0;">
	<div id="YMapsID-1357" style="width:600px;height:450px; margin: 0 auto;"></div>
</div>
<!-- Этот блок кода нужно вставить в ту часть страницы, где вы хотите разместить карту (конец) -->